name: flutter_yoapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.6
  audioplayers: ^6.0.0
  http: ^0.13.3
  flutter_dotenv: ^5.1.0
  google_sign_in: ^5.4.2
  googleapis: ^10.0.0
  google_generative_ai: ^0.0.1-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audios/fin.wav
    - assets/images/
    - assets/config/

  fonts:
    - family: ShillaCulture
      fonts:
        - asset: assets/fonts/Shilla_Culture(M).otf
          weight: 400
        - asset: assets/fonts/Shilla_Culture(B).otf
          weight: 700
